//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormStudent.EF_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public byte ID { get; set; }
        public string TC { get; set; }
        public string NAME_SURNAME { get; set; }
        public string PHONE { get; set; }
        public string ADRESS { get; set; }
        public string E_MAIL { get; set; }
    }
}
